# Generated by Django 4.2.30 on 2026-05-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_temperature_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemperatureAlert',
        ),
    ]
